config/routes.rb
Poc::Application.routes.draw do
  root to: "home#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :sessions=> "users/sessions"} 
  
  match 'follow' => 'users#follow'
match 'unfollow' => 'users#unfollow'
match 'like' => 'users#like'
  
  resource :user  do
	resources :statuses
	member do
		get  'change_password', as:  "change_password"
		put 'editprofile'
		get 'admin_allusers'
		get 'jsonuser'
		get 'quiz'
	
	end
	
  end
  
 match 'quizrem', to: "users#quizrem", :as  => "quizrem"
  resources :comments
  
  get '/home/generate_random_numbers' => "home#generate_random_numbers"
  get '/home/index/' => "home#index"
  devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :statuses
has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :fname, :lname, :picture, :resume
  # attr_accessible :title, :body
  
  has_attached_file :picture, :default_url => ActionController::Base.helpers.asset_path("missing.png")
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  #validates_attachment_content_type :picture, :content_type => /\Aimage/
  
   has_attached_file :resume, :default_url => ActionController::Base.helpers.asset_path("missing.png")
 validates_attachment_content_type :resume, :content_type =>['application/pdf', 'application/xlsx'], :message => ', Only PDF, EXCEL, WORD or TEXT files are allowed. '
 #do_not_validate_attachment_file_type :resume
 #do_not_validate_attachment_file_type :picture
  
acts_as_followable
acts_as_follower
acts_as_liker
  
  
  def self.from_omniauth(auth)
	where(provider: auth.provider, uid: auth.id).first_or_create do |user|
		user.email = auth.info.email
		user.password = Devise.friendly_token[0,20]
		 user.fname = auth.info.name
		 #user.image= auth.info.image
		 user.picture = process_uri(auth.info.image)
	end
 end
 
	def self.new_with_session(params, session)
		super.tap do |user|
			if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end
	
	def self.process_uri(uri)
		picture_url = URI.parse(uri)
		picture_url.scheme = 'https'
		picture_url.to_s
	end
	
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		@user  = User.from_omniauth(request.env["omniauth.auth"])
		
		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_filter :authenticate_user!, :only => [:edit, :update]
	 @@totalmarks =  0
	def admin_allusers
		if (current_user.id==1)
		@users=  User.paginate(:page => params[:page], :per_page => 5)
		@users =User.order(params[:user]).paginate(:page => params[:page], :per_page => 5) if params[:user].present?
		 @users=User.where(" fname LIKE :show OR email LIKE :show OR lname LIKE :show", { :show =>  "%#{params[:search]}%"  } ).paginate(:page => params[:page], :per_page => 5) if params[:search].present? 
		 else
			redirect_to root_path
		end
	end
	
	def new 
		@user = User.new 
	end
	
	def edit
		@user = User.find(params[:format])
	end
	
	
	def update
		@user =  current_user
		if @user.update_with_password(params[:user])
			redirect_to root_path, :notice => "Password updated successfully"
		else
			render :action => 'change_password' 
		end
	end
	
	def change_password
		@user = current_user	
	end
		
	def  editprofile
		#@user = User.find(params[:format])
		@user= User.find(params[:format])
		if @user.update_attributes(params[:user])
			redirect_to root_path, :notice => "Profile updated successfully"
		else
			render :action => 'edit'
		end
	end
	
	def show
		@user = User.find(params[:format])
	end	
	
	def destroy
		@user = User.find(params[:format])
		@user.destroy
		 redirect_to admin_allusers_user_url, :notice=> "User Deleted"
	end
	
	 def follow
		@user = User.find(params[:user])
		current_user.toggle_follow!(@user)
	end
	
	def unfollow
		@user = User.find(params[:user])
		current_user.unfollow!(@user)
	end
	
	 def like
		if params[:likeable_type] == "Status"
			@likeable = Status.find(params[:likeable_id])
		else
			@likeable = Comment.find(params[:likeable_id])
		end
		current_user.toggle_like!(@likeable)
	end
	
	def jsonuser
		@users = User.all
		render json: @users
	
	end
<<<<<<< HEAD
	
	def quizrem
		@marks = 0
		if params[:answer].present?
			answer  = Answer.find_by_id(params[:answer].to_i)
			@marks = answer.weightage
			@@totalmarks = @@totalmarks + @marks
=======
	def quizrem
		
		if params[:answer].present?
			answer  = Answer.find_by_id(params[:answer].to_i)
			marks = answer.weightage
			@@totalmarks = @@totalmarks + marks
>>>>>>> origin/master
		end
		
		@totalmarks = @@totalmarks
		id = params[:id].to_i + 1
		@question = Question.find_by_id(id)
		@@totalmarks = 0 if @question.nil?
		 respond_to do |format|
			format.js 
		end

	end
	
	def quiz
		@users = User.all
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%=  form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div data-alert class="alert-box alert">
<h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<h2><a href="#" class="close">&times;</a><h2>
</div>
<% end %>
<div class="field">
<%= f.label :current_password %><br />
<%= f.text_field :current_password %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %>
</div>
<div>
<%= f.submit "change Password", class: "button" %>
</div>
<% end %>

app/views/users/_question.html.erb
<%= form_tag quizrem_path(:id => question.id), :remote => true do |f| %>
	<b><%= question.id %></b>
	<%= question.content %><br/>
	<% question.answers.each do |answer| %>
		<br><%= radio_button_tag 'answer', answer.id %> <%= answer.content %>
	<% end %>
	<br/>
	<% if question.id == Question.last.id %>
		<%= submit_tag "finish", class: "button tiny" %>
	<% else %>
		<%= submit_tag "next", class: "button tiny" %>
	<% end %>
<% end %>

app/views/users/_user.html.erb
<table>
  <tr>
    <th>Email Id</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Created At</th>
    <th>Picture</th>
    <th>Resume</th>
  </tr>

<% @users.each do |user| %>
		<h3>
		<tr>
		<td><%= link_to user.email, user %></td>
		<td><%= user.fname %></td>
		<td><%= user.lname %></td>
		<td><%= user.created_at %></td>
		<td><%= link_to "View Picture", user.picture.url(:original, false) %></td>
		<td><%= link_to "Download Resume", user.resume.url(:original, false) %></td>
		<td><span class='actions'>
			<%= link_to "Edit", edit_user_path(user) %>
			<% if (user.id!=1) %>
			<%= link_to "Delete", user, :confirm=> "Are you sure?", :method => :delete %>
			<% end %>
		</span></td>
		</tr>
		
		</h3>
<% end %>
</table>
<%= will_paginate @users %>

app/views/users/admin_allusers.html.erb
<br/>
<ul>
<ul class="inline-list">

<li>Sort By:</li>

<li><%= link_to "Fname", :user => "fname", :id => 'sort', :remote => true %></li>
<li><%= link_to "ID", :user => "id", class: "sort", :remote => true %></li>
</ul>

<%= form_tag(admin_allusers_user_path, :method => "get", id: "search-form", :remote => true) do %>
  <ul class="inline-list">
  <li>

  <%= text_field_tag :search, params[:search], placeholder: "Search Users" %></li>
  <%#= submit_tag "Search", :name => nil %>
  <li><button type="submit" value="Search" class="button tiny large radius">search</button></li>
  </ul>
<% end %>
<div id="users" class="column">

<%= render :partial => "user" %>

</div>

app/views/users/admin_allusers.js.erb
$("#users").html("<%= escape_javascript(render :partial => "user") %>"); 

app/views/users/change_password.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
<h1> Edit Password </h1>
<%= render 'form' %> 
</div>

app/views/users/edit.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
<h1> Edit Profile </h1>
<%=  form_for(@user, :url => editprofile_user_path(@user), :html=>{:multipart=>true}) do |f| %>
<% if @user.errors.any? %>
<div id="errorExplanation">
<h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="mb1">
<%= f.label :fName %>
<%= f.text_field :fname, autofocus: true %>
</div>
<div class="mb1">
<%= f.label :lname %>
<%= f.text_field :lname, autofocus: true %>
</div>
<div class="mb1">
<%= f.label :email %>
<%= f.text_field :email, autofocus: true %>
</div>
<div class="mb1">
<%= f.label :picture %><br />
<%= f.file_field :picture %>
</div>
<div class="mb1">
<%= f.label :resume %><br />
<%= f.file_field :resume %>
</div>
<%= f.hidden_field :id, :value => @user.id %>
<div class="actions">
<%= f.submit "Submit" %>
</div>
</div>
<% end %>

app/views/users/follow.js.erb
$('.user-<%= @user.id %> > #follow_form').html("<%= escape_javascript(render 'shared/follow', user: @user )%>")

app/views/users/like.js.erb
$('.<%= @likeable.class %>-<%= @likeable.id %> > #like_form').html("<%= escape_javascript(render 'shared/like_form', likeable: @likeable) %>")
$('.<%= @likeable.class %>-<%= @likeable.id %> > .likes').html("<%= pluralize(@likeable.likers(User).count, 'like')%>")

app/views/users/quiz.html.erb
<div class="row">
<br/>
<br/>
<%= link_to 'Load Question', "#", :id => 'quizload' %>
<<<<<<< HEAD
<%= hidden_field_tag :score, "0" %>
<div id="questions">

=======
<div id="questions">
>>>>>>> origin/master
hi
</div>
</div>

app/views/users/quizrem.js.erb
<<<<<<< HEAD
var old = parseInt($('#score').val());
$('#score').val(old+<%= @marks %>);

$('#quizload').hide();
<% if @question.nil? %>
	$('#questions').html('Thanks');
	alert('Your Score..' + $('#score').val());
=======
$('#quizload').hide();
<% if @question.nil? %>
	$('#questions').html('Thanks');
	$('#questions').html(alert('Your Score : '+ <%= @totalmarks %>));
>>>>>>> origin/master
<% else %>
	$('#questions').html("<%= escape_javascript(render(:partial => 'question', :locals => {:question => @question})) %>");
<% end %>

app/views/users/show.html.erb
<h2> User Details </h2>
<div class="left">
<%= render 'shared/follow_form', user: @user %>
</div>
<%= div_for @user do %>
	<br/><br/>
	<div class="large-3 small-12 column">
  <b>Profile Picture: </b><%=image_tag @user.picture.url%><br/>
</div>
<div class="large-9 small-12 column">
	<h3><b>First Name:</b><%= @user.fname %> <br/>
	<b>Last Name:	</b><%= @user.lname %> <br/>
	<b>Email:	</b><%= @user.email %> <br/>
	<b>User Creation Time: </b><%= @user.created_at %> <br/>
		
		<span class='actions'>
			<%= link_to "Edit", edit_user_path(@user) %>
			<%= link_to "Delete", @user, :confirm=> "Are you sure?", :method => :delete %>
		</span>
	</h3>
	</div>
<% end %>

app/views/users/unfollow.js.erb
$('.user-<%= @user.id %> > #follow_form').html("<%= escape_javascript(render 'shared/follow', user: @user) %>")