config/routes.rb
Poc::Application.routes.draw do
  root to: "home#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :sessions=> "users/sessions"} 
  
  match 'follow' => 'users#follow'
match 'unfollow' => 'users#unfollow'
match 'like' => 'users#like'
  
  resource :user  do
	resources :statuses
	member do
		get  'change_password', as:  "change_password"
		put 'editprofile'
		get 'admin_allusers'
		get 'jsonuser'
		get 'quiz'
	
	end
	
  end
  
 match 'quizrem', to: "users#quizrem", :as  => "quizrem"
  resources :comments
  
  get '/home/generate_random_numbers' => "home#generate_random_numbers"
  get '/home/index/' => "home#index"
  devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :status
  belongs_to :user
  attr_accessible :content, :status_id
  acts_as_likeable
 include PublicActivity::Model
tracked owner: ->(controller, model) { controller && controller.current_user }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :destroy]

	def create
		@status = Status.find(params[:comment][:status_id])
		@comment = Comment.new(params[:comment])
		@comment.user = current_user
		@comment.save
		redirect_to root_path
end
		


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/public_activity/comment/_create.html.erb
<% if activity.trackable %>
<div class="user-box">
<%#= image_tag activity.owner.picture.url(:thumb), class: 'like_profile' %>
<img src="http://placehold.it/80x80&text=[img]"/>
<%= link_to activity.owner.fname, activity.owner %>
commented on post <%= link_to activity.trackable.likeable.class, user_status_path(activity.trackable.post) %>
</div>
<div class="like_post">
<%= render 'comments/comment', comment: activity.trackable %>
</div>
<% end %>