config/routes.rb
Poc::Application.routes.draw do
  root to: "home#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :sessions=> "users/sessions"} 
  
  match 'follow' => 'users#follow'
match 'unfollow' => 'users#unfollow'
match 'like' => 'users#like'
  
  resource :user  do
	resources :statuses
	member do
		get  'change_password', as:  "change_password"
		put 'editprofile'
		get 'admin_allusers'
		get 'jsonuser'
		get 'quiz'
	
	end
	
  end
  
 match 'quizrem', to: "users#quizrem", :as  => "quizrem"
  resources :comments
  
  get '/home/generate_random_numbers' => "home#generate_random_numbers"
  get '/home/index/' => "home#index"
  devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question_id, :weightage
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :status
  belongs_to :user
  attr_accessible :content, :status_id
  acts_as_likeable
 include PublicActivity::Model
tracked owner: ->(controller, model) { controller && controller.current_user }
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
	
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
include PublicActivity::Model
tracked owner: ->(controller, model) { controller && controller.current_user }
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content
  has_many :answers
end

app/models/status.rb
class Status < ActiveRecord::Base
belongs_to :user
has_many :comments
 attr_accessible :post, :posted_at, :user_id
 acts_as_likeable
  include PublicActivity::Model
tracked owner: ->(controller, model) { controller && controller.current_user }
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :statuses
has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :fname, :lname, :picture, :resume
  # attr_accessible :title, :body
  
  has_attached_file :picture, :default_url => ActionController::Base.helpers.asset_path("missing.png")
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  #validates_attachment_content_type :picture, :content_type => /\Aimage/
  
   has_attached_file :resume, :default_url => ActionController::Base.helpers.asset_path("missing.png")
 validates_attachment_content_type :resume, :content_type =>['application/pdf', 'application/xlsx'], :message => ', Only PDF, EXCEL, WORD or TEXT files are allowed. '
 #do_not_validate_attachment_file_type :resume
 #do_not_validate_attachment_file_type :picture
  
acts_as_followable
acts_as_follower
acts_as_liker
  
  
  def self.from_omniauth(auth)
	where(provider: auth.provider, uid: auth.id).first_or_create do |user|
		user.email = auth.info.email
		user.password = Devise.friendly_token[0,20]
		 user.fname = auth.info.name
		 #user.image= auth.info.image
		 user.picture = process_uri(auth.info.image)
	end
 end
 
	def self.new_with_session(params, session)
		super.tap do |user|
			if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end
	
	def self.process_uri(uri)
		picture_url = URI.parse(uri)
		picture_url.scheme = 'https'
		picture_url.to_s
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #before_filter :authenticate_user!
  
 include PublicActivity::StoreController
# ...
hide_action :current_user
  
  def after_sign_in_path_for(resource)
     path = (resource.id ==  1) ? admin_allusers_user_path : root_path
     return path
	
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :destroy]

	def create
		@status = Status.find(params[:comment][:status_id])
		@comment = Comment.new(params[:comment])
		@comment.user = current_user
		@comment.save
		redirect_to root_path
end
		


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!
	
	def index
		if user_signed_in?
			if (current_user.id==1)
			redirect_to admin_allusers_user_path
			end
			@user= current_user
			followees_ids = current_user.followees(User).map(&:id)
			@activities = PublicActivity::Activity.where(owner_id: followees_ids, owner_type: "User")
		else
			
			@message= "Welcome"
	#	render :layout => false
		end
	end
	
	def generate_random_numbers
		
	#	render :text => "Random No: #{rand(1..50)}"
	end
	
	

end

app/controllers/onboarding_approved_rejected_requests_controller.rb
class OnboardingApprovedRejectedRequestsController < ApplicationController
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

	def create 
		@status = current_user.statuses.new(params[:status]) 
		if @status.save 
			render 'create'
		else 
			respond_to do |format|
				format.html { redirect_to root_path, :alert => 'Unable to add comment'  }
				format.js { render 'fail_create.js.erb' }
			end 
		end 
	end
	
	def show
		 @comment = Comment.new
		@status = Status.find(params[:id])
		@comments = @status.comments

		respond_to do |format|
			format.html 
			format.json { render json: @status }
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_filter :authenticate_user!, :only => [:edit, :update]
	 @@totalmarks =  0
	def admin_allusers
		if (current_user.id==1)
		@users=  User.paginate(:page => params[:page], :per_page => 5)
		@users =User.order(params[:user]).paginate(:page => params[:page], :per_page => 5) if params[:user].present?
		 @users=User.where(" fname LIKE :show OR email LIKE :show OR lname LIKE :show", { :show =>  "%#{params[:search]}%"  } ).paginate(:page => params[:page], :per_page => 5) if params[:search].present? 
		 else
			redirect_to root_path
		end
	end
	
	def new 
		@user = User.new 
	end
	
	def edit
		@user = User.find(params[:format])
	end
	
	
	def update
		@user =  current_user
		if @user.update_with_password(params[:user])
			redirect_to root_path, :notice => "Password updated successfully"
		else
			render :action => 'change_password' 
		end
	end
	
	def change_password
		@user = current_user	
	end
		
	def  editprofile
		#@user = User.find(params[:format])
		@user= User.find(params[:format])
		if @user.update_attributes(params[:user])
			redirect_to root_path, :notice => "Profile updated successfully"
		else
			render :action => 'edit'
		end
	end
	
	def show
		@user = User.find(params[:format])
	end	
	
	def destroy
		@user = User.find(params[:format])
		@user.destroy
		 redirect_to admin_allusers_user_url, :notice=> "User Deleted"
	end
	
	 def follow
		@user = User.find(params[:user])
		current_user.toggle_follow!(@user)
	end
	
	def unfollow
		@user = User.find(params[:user])
		current_user.unfollow!(@user)
	end
	
	 def like
		if params[:likeable_type] == "Status"
			@likeable = Status.find(params[:likeable_id])
		else
			@likeable = Comment.find(params[:likeable_id])
		end
		current_user.toggle_like!(@likeable)
	end
	
	def jsonuser
		@users = User.all
		render json: @users
	
	end
<<<<<<< HEAD
	
	def quizrem
		@marks = 0
		if params[:answer].present?
			answer  = Answer.find_by_id(params[:answer].to_i)
			@marks = answer.weightage
			@@totalmarks = @@totalmarks + @marks
=======
	def quizrem
		
		if params[:answer].present?
			answer  = Answer.find_by_id(params[:answer].to_i)
			marks = answer.weightage
			@@totalmarks = @@totalmarks + marks
>>>>>>> origin/master
		end
		
		@totalmarks = @@totalmarks
		id = params[:id].to_i + 1
		@question = Question.find_by_id(id)
		@@totalmarks = 0 if @question.nil?
		 respond_to do |format|
			format.js 
		end

	end
	
	def quiz
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/onboarding_approved_rejected_requests_helper.rb
module OnboardingApprovedRejectedRequestsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>



  <body>

 

<script type="text/javascript">
//window.onload = function() {
//	var toppos = [0,50]
//	var rand = pos[Math.floor(Math.random() * pos.length)];
//	  document.getElementById("game").onclick = function() {
//	var	pos=100;
 //       document.getElementById("game").style.top=rand+"%"; 
//		document.getElementById("game").style.left=rand+"%"; 
//alert('hello');

	
	
	function cg()
	{ 
	var m = document.getElementsByTagName('meta');
	for (i=0; i<m.length; i++) { 
      if (m[i].getAttribute("name") == "vieport") { 
         return alert(m[i].getAttribute("content")); 
      } 
   } 
	//alert(m.getAttribute(c);
		var pos = [4,screen.width]
	var rand = pos[Math.floor(Math.random() * pos.length)];
	document.getElementById("game").style.top=rand+"px"; 
	var rand = pos[Math.floor(Math.random() * pos.length)];
	document.getElementById("game").style.left=rand+"px"; 
	}
	
     
//}
</script>


  <div>
  <nav class="top-bar column" data-topbar>
 
      <ul class="title-area">
        <li class="name">
          <h1>
            <a href="/">
              <i class="fi-play-video"></i> Blog
            </a>
          </h1>
        </li>
        <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
      </ul>
 
      <section class="top-bar-section">
        <ul class="right">
        <%if signed_in?%>
			<li><%= link_to "Change Password", change_password_user_path %></li>
			<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
			<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
			<li><%= link_to "Quiz", quiz_user_path %></li> 
			<%else%>
			<li><%= link_to "Login", new_user_session_path %></li>
			<li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)%></li>
			<li><%= link_to "Generate Random Number", '#', :id => "randno" %></li>
		<%end%>
      </section>
 
    </nav>
</div>
 <div id="main-content" class="row full-min-height">

<% if user_signed_in? %>
	<% if current_user.id==1 %>
		<%= "Welcome Admin" %>
	<% else %>
		<%= "Hi, #{current_user.fname} " %>
	<% end %>
<% end %>
  </div>

  <%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>
<div style="position: relative; width:100% id="divgame">
	 <img id="game" src="assets/missing.png" alt="game image" style="position:absolute; z-index: 1; top:4px height:110px width:110px; left:4px" onclick=cg() />
</div>
    <%= yield %>
 
    
    <%= javascript_include_tag "application" %>
	<%= javascript_include_tag "vendor/modernizr" %>
  </body>
</html>

app/views/shared/_follow.html.erb
<% if current_user.follows?(user) %>
<%= button_to "Follow", follow_path(user: user.id) , remote: true, method: :get , class: "button tiny" %>
<% else %>
<%= button_to "UnFollow", follow_path(user: user.id) , remote: true, method: :get , class: "button tiny" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% if current_user != user %>
<div class="user-<%= user.id %>">
	<div id="follow_form">
	
		<%= render 'shared/follow', user: user %>

		<%# render 'shared/follow', user: user %>
	
	</div>
</div>
<% end %>

app/views/shared/_form.html.erb
<% @comment = Comment.new %>
<%= form_for @comment do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
<% @comment.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<%= f.hidden_field :status_id, value: status.id %>
<div class="field">
<%= f.text_field :content %>
</div>
<div class="actions">
<%= f.submit "comment", class: 'button tiny large' %>
</div>
<% end %>

app/views/shared/_like_form.html.erb
<% if user_signed_in? %>
<div id="like_form">
	<% if current_user.likes?(likeable) %>
		<%= link_to "unlike", like_path(likeable_id: likeable.id, likeable_type: likeable.class) , remote: true, method: :get , class: "like" %>
	<% else %>
		<%= link_to "like", like_path(likeable_id: likeable.id, likeable_type: likeable.class) , remote: true, method: :get , class: "like" %>
	<% end %>
</div>
<% end %>

app/views/shared/_unfollow.html.erb
<%= button_to "UnFollow", follow_path(user: user.id) , remote: true, method: :get , class: "small button" %>